#!/bin/bash
echo "Please enter your number of files (rounds)"
read rounds

mkdir "reverse_upload"

for i in $(seq 1 $rounds); do

echo "Please enter the file name for file $i"
read name
echo "Your filename is $name"
cp -R ~/Desktop/$name ~/Desktop/reverse_upload/$name
cd ~/Desktop/reverse_upload

myfilesize=$(stat -f %z $name)

split -b $((myfilesize / 2000000))m $name round$i 

done


